name: Install Statediff
description: Install Statediff for Filecoin Lotus

runs:
  using: composite
  steps:
    - id: statediff
      run: mktemp -d | xargs -I{} echo "path={}" | tee -a $GITHUB_OUTPUT
      shell: bash
    - env:
        STATEDIFF_PATH: ${{ steps.statediff.outputs.path }}
      run: |
        git clone https://github.com/filecoin-project/statediff.git $STATEDIFF_PATH
        pushd $STATEDIFF_PATH
        go install ./cmd/statediff
        popd
      shell: bash
      continue-on-error: true
