name: Build

on:
  pull_request:
  push:
    branches:
      - master
      - release/*
      - circleci-gha-tests
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: ./.github/actions/install-ubuntu-deps
      - uses: ./.github/actions/install-go
      - uses: actions/cache@v4
        with:
          key: ${{ github.workflow }}-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          restore-keys: |
            ${{ github.workflow }}-${{ runner.os }}-go-
      - run: make deps lotus
