name: Test

on:
  pull_request:
  push:
    branches:
      - master
      - release/*
      - circleci-gha-tests
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  discover:
    name: Discover Test Groups
    runs-on: ubuntu-latest
    outputs:
      groups: ${{ steps.test.outputs.groups }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: ./.github/actions/install-go
      - id: test
        env:
          CONFIG: |
            [
              {
                "name": "multicore-sdr",
                "packages": ["./storage/sealer/ffiwrapper"],
                "go_test_flags": "-run=TestMulticoreSDR",
                "test_rustproofs_logs": "1"
              }, {
                "name": "conformance",
                "packages": ["./conformance"],
                "go_test_flags": "-run=TestConformance",
                "skip_conformance": "0",
                "format": "pkgname-and-test-fails",
                "needs_params": true,
                "needs_statediff": true
              }, {
                "name": "itest-worker",
                "runner": ["self-hosted", "linux", "x64", "2xlarge"],
                "skip": false
              }, {
                "name": "itest-sector_import_full",
                "runner": ["self-hosted", "linux", "x64", "2xlarge"],
                "skip": false
              }, {
                "name": "itest-sector_import_simple",
                "runner": ["self-hosted", "linux", "x64", "2xlarge"],
                "skip": false
              }, {
                "name": "itest-sector_pledge",
                "runner": ["self-hosted", "linux", "x64", "2xlarge"],
                "skip": false,
                "needs_params": true
              }, {
                "name": "itest-wdpost",
                "runner": ["self-hosted", "linux", "x64", "2xlarge"],
                "skip": false,
                "needs_params": true
              }, {
                "name": "itest-harmonydb",
                "needs_yugabyte": true
              }, {
                "name": "itest-harmonytask",
                "needs_yugabyte": true
              }, {
                "name": "unit-node",
                "packages": ["./node/..."]
              }, {
                "name": "unit-storage",
                "runner": ["self-hosted", "linux", "x64", "2xlarge"],
                "skip": false,
                "packages": ["./storage/...", "./extern/..."],
                "needs_params": true
              }, {
                "name": "unit-cli",
                "packages": ["./cli/...", "./cmd/...", "./api/..."],
                "needs_params": true
              }, {
                "name": "unit-rest"
              }
            ]
        run: go run ./.github/scripts/extend-test-groups.go -config "$CONFIG" -output "$GITHUB_OUTPUT" -skip true
  test:
    needs: [discover]
    name: Test (${{ matrix.name }})
    runs-on: ${{ matrix.runner || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.discover.outputs.groups) }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: ./.github/actions/install-ubuntu-deps
      - uses: ./.github/actions/install-go
      - run: go install gotest.tools/gotestsum@latest
      - run: make deps
      - if: ${{ matrix.needs_params }}
        uses: ./.github/actions/fetch-params
      - if: ${{ matrix.needs_yugabyte }}
        uses: ./.github/actions/start-yugabyte
        timeout-minutes: 3
      # TODO: Install statediff (used to be used for conformance)
      - id: reports
        run: mktemp -d | xargs -0 -I{} echo "path={}" | tee -a $GITHUB_OUTPUT
      # TODO: Track coverage (used to be tracked for conformance)
      - env:
          NAME: ${{ matrix.name }}
          LOTUS_SRC_DIR: ${{ github.workspace }}
          LOTUS_HARMONYDB_HOSTS: 127.0.0.1
          REPORTS_PATH: ${{ steps.reports.outputs.path }}
          SKIP_CONFORMANCE: ${{ matrix.skip_conformance || 1 }}
          TEST_RUSTPROOFS_LOGS: ${{ matrix.test_rustproofs_logs || 0 }}
          FORMAT: ${{ matrix.format || 'standard-verbose' }}
          PACKAGES: ${{ join(matrix.packages, ' ') }}
        run: |
          gotestsum \
            --format "$FORMAT" \
            --junitfile "$REPORTS_PATH/$NAME.xml" \
            --jsonfile "$REPORTS_PATH/$NAME.json" \
            --packages="$PACKAGES" \
            -- ${{ matrix.go_test_flags || '' }}
      - if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: |
            ${{ steps.reports.outputs.path }}/${{ matrix.name }}.xml
            ${{ steps.reports.outputs.path }}/${{ matrix.name }}.json
        continue-on-error: true
