name: Test

on:
  pull_request:
  push:
    branches:
      - master
      - release/*
      - circleci-gha-tests
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  discover:
    name: Discover Test Groups
    runs-on: ubuntu-latest
    outputs:
      groups: ${{ steps.test.outputs.groups }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - id: test
        env:
          # Unit test groups other than unit-rest
          utests: |
            [
              {"name": "unit-cli", "packages": ["./cli/...", "./cmd/...", "./api/..."]},
              {"name": "unit-storage", "packages": ["./storage/...", "./extern/..."]},
              {"name": "unit-node", "packages": ["./node/..."]}
            ]
          # Other tests that require special configuration
          otests: |
            [
              {
                "name": "multicore-sdr",
                "packages": ["./storage/sealer/ffiwrapper"],
                "go_test_flags": "-run=TestMulticoreSDR",
                "test_rustproofs_logs": "1"
              }, {
                "name": "conformance",
                "packages": ["./conformance"],
                "go_test_flags": "-run=TestConformance",
                "skip_conformance": "0"
              }
            ]
          # Mapping from test group names to custom runner labels
          runners: |
            {
              "itest-worker": ["self-hosted", "linux", "x64", "2xlarge"],
              "itest-sector_pledge": ["self-hosted", "linux", "x64", "4xlarge"],
              "itest-wdpost": ["self-hosted", "linux", "x64", "4xlarge"],
              "unit-storage": ["self-hosted", "linux", "x64", "2xlarge"]
            }
          # A list of test groups that require YugabyteDB to be running
          yugabytedb: |
            ["itest-harmonydb", "itest-harmonytask"]
        run: |
          # Create a list of integration test groups
          itests="$(
            find ./itests -name "*_test.go" | \
              jq -R '{
                "name": "itest-\(. | split("/") | .[2] | sub("_test.go$";""))",
                "packages": [.]
              }' | jq -s
            )"

          # Create a list of packages that are covered by the integration and unit tests
          packages="$(jq -n 'env.utests | fromjson | map(.packages) | flatten | . + ["./itests/..."]')"

          # Create a new group for the unit tests that are not yet covered
          urest="$(
            find . -name "*_test.go" | cut -d/ -f2 | sort | uniq | \
              jq -R '"./\(.)/..."' | \
              jq -s '{"name": "unit-rest", "packages": (. - (env.packages | fromjson))}'
          )"

          # Combine the groups for integration tests, unit tests, the new unit-rest group, and the other tests
          groups="$(jq -n '(env.itests | fromjson) + (env.utests | fromjson) + [env.urest | fromjson] + (env.otests | fromjson)')"

          # Apply custom runner labels to the groups
          groups="$(jq -n 'env.groups | fromjson | map(. + {"runner": (.name as $name | env.runners | fromjson | .[$name]) })')"

          # Apply the needs_yugabytedb flag to the groups
          groups="$(jq -n 'env.groups | fromjson | map(. + {"needs_yugabytedb": ([.name] | inside(env.yugabytedb | fromjson)) })')"

          # Output the groups
          echo "groups=$groups"
          echo "groups=$(jq -nc 'env.groups | fromjson')" >> $GITHUB_OUTPUT
  fetch:
    name: Fetch Proof Prameters
    runs-on: ubuntu-latest
    outputs:
      key: ${{ steps.cache.outputs.key }}
      path: ${{ steps.cache.outputs.path }}
    steps:
      - id: cache
        run: |
          echo "key=v26-2k-lotus-params" | tee -a $GITHUB_OUTPUT
          echo "path=/var/tmp/filecoin-proof-parameters/" | tee -a $GITHUB_OUTPUT
      - id: params
        uses: actions/cache/restore@v4
        with:
          key: ${{ steps.cache.outputs.key }}
          path: ${{ steps.cache.outputs.path }}
          lookup-only: true
      - if: steps.params.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - if: steps.params.outputs.cache-hit != 'true'
        uses: ./.github/actions/install-ubuntu-deps
      - if: steps.params.outputs.cache-hit != 'true'
        uses: ./.github/actions/install-go
      - if: steps.params.outputs.cache-hit != 'true'
        run: make lotus
      - if: steps.params.outputs.cache-hit != 'true'
        run: ./lotus fetch-params 2048
      - if: steps.params.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.cache.outputs.key }}
          path: ${{ steps.cache.outputs.path }}
  test:
    needs: [discover, fetch]
    name: Test (${{ matrix.name }})
    runs-on: ${{ github.repository == 'filecoin-project/lotus' && matrix.runner || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.discover.outputs.groups) }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: ./.github/actions/install-ubuntu-deps
      - uses: ./.github/actions/install-go
      - run: go install gotest.tools/gotestsum@latest
      - run: make deps
      - uses: actions/cache/restore@v4
        with:
          key: ${{ needs.fetch.outputs.key }}
          path: ${{ needs.fetch.outputs.path }}
          fail-on-cache-miss: true
      - if: ${{ matrix.needs_yugabytedb }}
        uses: ./.github/actions/start-yugabytedb
        timeout-minutes: 3
      # TODO: Install statediff (used to be used for conformance)
      - id: reports
        run: mktemp -d | xargs -0 -I{} echo "path={}" | tee -a $GITHUB_OUTPUT
      # TODO: Track coverage (used to be tracked for conformance)
      - env:
          NAME: ${{ matrix.name }}
          LOTUS_SRC_DIR: ${{ github.workspace }}
          LOTUS_HARMONYDB_HOSTS: 127.0.0.1
          REPORTS_PATH: ${{ steps.reports.outputs.path }}
          SKIP_CONFORMANCE: ${{ matrix.skip_conformance || '1' }}
          TEST_RUSTPROOFS_LOGS: ${{ matrix.test_rustproofs_logs || '0' }}
          FORMAT: ${{ matrix.format || 'standard-verbose' }}
          PACKAGES: ${{ join(matrix.packages, ' ') }}
        run: |
          gotestsum \
            --format "$FORMAT" \
            --junitfile "$REPORTS_PATH/$NAME.xml" \
            --jsonfile "$REPORTS_PATH/$NAME.json" \
            --packages="$PACKAGES" \
            -- ${{ matrix.go_test_flags || '' }}
      - if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: |
            ${{ steps.reports.outputs.path }}/${{ matrix.name }}.xml
            ${{ steps.reports.outputs.path }}/${{ matrix.name }}.json
        continue-on-error: true
